### PR TITLE
Access API over HTTP

### PR DESCRIPTION
**Pull request by leonoverweel**
This PR adds the ability to access the OpenDC API over HTTP (instead of just over our custom layer on top of websockets).

It also updates the documentation, and a Postman collection that can be used to test the web server over HTTP (much better experience).

### CODE REVIEW

**Comment by leonoverweel** [comment]
@sacheendra could you review this and see if, following the setup guide in the `README`, you're able to send a request through Postman? If it looks good, please merge.

**Comment by sacheendra** [comment]
@leonoverweel When there is an error, the returned 500 response is actually an HTML response. This may cause problems while programatically parsing responses. Can you make it such that all responses, error or normal, are in JSON?

**Comment by sacheendra** [comment]
The starting of the server is uneventful. But, when I try to run the postman tests using the included collection I get a 500 error. 

The stacktrace visible in the console is
```
(odc-scratch) opendc-web-server $python main.py test.json
(42668) wsgi starting up on http://0.0.0.0:8081
(42668) accepted ('127.0.0.1', 55164)
[2017-04-02 20:36:39,507] ERROR in app: Exception on /api/v1/simulations [POST]
Traceback (most recent call last):
  File "/Users/sacheendra/Workspace/openDC/odc-scratch/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sacheendra/Workspace/openDC/odc-scratch/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sacheendra/Workspace/openDC/odc-scratch/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sacheendra/Workspace/openDC/odc-scratch/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sacheendra/Workspace/openDC/odc-scratch/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 138, in api_call
    req.method,
AttributeError: 'dict' object has no attribute 'method'
```

**Comment by leonoverweel** [comment]
@sacheendra this was an error in handling wrong requests. You didn't put in your authentication token, which should have returned a `401`, but instead crashed the server. It now properly returns a `401`. (But do remember to put in your authentication token for testing, see the [setup the guide in `README`](https://github.com/atlarge-research/opendc-web-server/tree/api-over-http#set-up-postman).)

**Comment by sacheendra** [comment]
screen shot 2017-04-03 at 2 40 44 pm

Still get the error. Is there something I am missing?

**Comment by sacheendra** [comment]
Add a step to the setup to register a new user. As adding a new simulation requires a user.

**Comment by sacheendra** [comment]
Return the correct HTTP error code apart from just returning it as a field in the returned object.

**Comment by sacheendra** [comment]
Info: The cause of the issue above was that I used different google client id in my config.json and the index.html page. The google client ids at both places need to be the same. This was resolved in an offline discussion.

**Comment by leonoverweel** [comment]
@sacheendra regarding your comments:

* Commit d1314ab removes `googleId` as required parameter to make a new user; the only requirement is now an email address.
* Commit 2a49540 adds instructions to first make an account before sending requests.
* Commit fd0376c makes the server return proper status codes if something goes wrong, instead of just a `200` with the error in the JSON body.

If this fixes your issues, please merge.

**Pull request merged**
